
//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SimulationExam.Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ActivityDate
{

    public int Id { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<int> ActivityId { get; set; }



    public virtual Activity Activity { get; set; }

}

}
