

//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SimulationExam.Web.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SimulationExamEntities : DbContext
{
    public SimulationExamEntities()
        : base("name=SimulationExamEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Activity> Activity { get; set; }

    public virtual DbSet<ActivityDate> ActivityDate { get; set; }

    public virtual DbSet<Event> Event { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<UserActivity> UserActivity { get; set; }

}

}

